<? foreach ($C->other_users as $other_user) { ?>
	<br>
	<div class="boxline">
		<label class="required" style="line-height: 1.4em;"><?=
			h($other_user->username) ?>:</label>
		<div class="d" id="notes_user_<?= h($other_user->username) ?>"
			style="line-height: 1.4em;">
		<? if ($other_user->upcoming_notes == "") { ?>
			<span class="na">No notes entered.</span>
		<? } else { ?>
			<?= nl2br(h($other_user->upcoming_notes)) ?>
		<? } ?>
		</div>
	</div>
<? } ?>
