<p>
<div style="float: right;">
	<a href="#" onclick="toggle_notes_updating(); return false;"
		id="notes_status">Start auto-refreshing other notes</a>
</div>
<h3>Upcoming Show Notes/Scratch</h3>

<div class="box">
	<? $form->form_tag(ADMIN_ROOT_URL . "update_notes", array(),
	function($f) use ($C) { ?>
		<div class="boxline">
			<?= $f->label_tag("private_notes", "Private:",
				array("class" => "required")); ?>
			<?= $f->text_area_tag("private_notes", $C->user->private_notes,
				array("class" => "variable",
				"style" => "width: 75%; line-height: 1.3em; height: " .
				((max(substr_count($C->user->private_notes,
					"\n"), 8) * 1.5) + 2) .
				"em; font-size: 9pt;")); ?>
			<br>
		</div>
		<div class="boxline">
			<?= $f->label_tag("upcoming_notes", "Shared:",
				array("class" => "required")); ?>
			<?= $f->text_area_tag("upcoming_notes", $C->user->upcoming_notes,
				array("class" => "variable",
				"style" => "width: 75%; line-height: 1.3em; height: " .
				((max(substr_count($C->user->upcoming_notes,
					"\n"), 8) * 1.5) + 2) .
				"em; font-size: 9pt;")); ?>
			<br>
			<?= $f->submit_tag("Save"); ?>
		</div>
	<? }); ?>

	<div id="other_notes">
		<?= $C->render(array("partial" => "notes")); ?>
	</div>
</div>

<script>
	var updater;
	function toggle_notes_updating() {
		if (updater) {
			updater.stop();
			updater = null;
			$("notes_status").innerHTML =
				$("notes_status").innerHTML.replace(/Stop/, "Start");
		}
		else {
			updater = new Ajax.PeriodicalUpdater("other_notes",
				"<?= ADMIN_ROOT_URL ?>other_notes", {
				method: "get",
				frequency: 2,
			});
			$("notes_status").innerHTML =
				$("notes_status").innerHTML.replace(/Start/, "Stop");
		}
	}

	<? if (date("D") == "Thu" && date("G") >= 18 && date("G") <= 21) { ?>
		toggle_notes_updating();
	<? } ?>
</script>

<p>
<h3>Show Prompts</h3>
</p>

<div class="box">
<?= nl2br(h(Settings::fetch()->replaced_prompts)); ?>
</div>

<h3>Past Episodes (<a href="<?= ADMIN_ROOT_URL ?>episodes/build">Create New</a>)</h3>

<ul>
<? foreach ($C->episodes as $episode) { ?>
	<li><a href="<?= ADMIN_ROOT_URL ?>episodes/edit/<?= $episode->episode ?>"><?=
		$episode->episode ?>: <?= h($episode->title) ?></a>
		(<?= $episode->air_date->format("Y-m-d") ?>)
		<? if ($episode->is_pending) { ?>
			(<strong>PENDING</strong>)
		<? } ?>
<? } ?>
</ul>


<h3>Episode Download Statistics</h3>

<iframe style="margin-left: 1em; margin-right: 3em; width: 95%; height: 200px;
	border: 0; overflow: hidden;"
	src="https://countinual.com/jcs/counters/garbage.downloads?embed=1"></iframe>
