<!doctype html>
<html lang="en">
<head>
	<title><?= h($C->settings()->name) ?><?= $C->page_title ? ": " .
		h($controller->page_title) : "" ?></title>
	<meta http-equiv="content-type" content="text/html; charset=utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<link rel="shortcut icon" href="/garbage.png" />
	<?= $html->stylesheet_link_tag(array("application")); ?>
	<?= $html->javascript_include_tag(array("prototype")); ?>
</head>
<body>
	<div id="wrapper">
		<div id="header">
			<div id="headerright">
				<? if ($C->user) { ?>
					Logged in as
					<?= h($C->user->username); ?>
					<br>
					<a href="<?= ADMIN_ROOT ?>profile/">Edit Profile</a>
					|
					<?= $html->link_to("Logout",
						ADMIN_ROOT . "logout",
						array("confirm" => "Are you sure you want to logout?",
							"method" => "post")); ?>
				<? } else { ?>
					<?= $html->link_to("Login", ADMIN_ROOT . "login"); ?>
				<? } ?>
			</div>

			<h2><a href="<?= ADMIN_ROOT ?>"><?= h($C->settings()->name) ?>
				- Administration</a></h2>

			<div class="clear"></div>
		</div>
		<div id="subheader">
			<? if ($C->user) { ?>
				<div style="float: right;">
					<a href="<?= ADMIN_ROOT ?>show_settings">Edit Show
					Settings</a>
				</div>
				<a href="<?= $C->settings()->url ?>">View public site</a>
				|
				<a href="<?= ADMIN_ROOT ?>flushcache">Purge Homepage/RSS
					Caches</a>
			<? } else { ?>
				&nbsp;
			<? } ?>
		</div>

		<div id="inside">
			<?php echo $html->flash_errors(); ?>
			<?php echo $html->flash_notices(); ?>
			<?php echo $html->flash_successes(); ?>

			<?php echo $content_for_layout; ?>
		</div>

		<div id="footer">
			Copyright &copy; 2015 joshua stein
		</div>
	</div>
</body>
</html>
