<!doctype html>
<html lang="en">
<head>
	<title><?= h($C->settings()->name) ?><?= $C->page_title ? ": " .
		h($controller->page_title) : "" ?></title>
	<meta http-equiv="content-type" content="text/html; charset=utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<link rel="shortcut icon" href="/garbage.png" />
	<?php echo $html->stylesheet_link_tag(array("application")); ?>
	<?php echo $html->javascript_include_tag(array("prototype")); ?>
</head>
<body>
	<div id="wrapper">
		<div id="header">
			<div id="headerright">
				<? if ($controller->user) { ?>
					Logged in as
					<?= h($controller->user->username); ?>
					<br>
					<?= $html->link_to("Logout",
						array("controller" => "admin", "action" => "logout"),
						array("confirm" => "Are you sure you want to logout?",
							"method" => "post")); ?>
				<? } else { ?>
					<?= $html->link_to("Login", ADMIN_ROOT . "login"); ?>
				<? } ?>
			</div>

			<h1><a href="<?= ADMIN_ROOT ?>"><?= h($C->settings()->name) ?>
				- Administration</a></h1>

			<div class="clear"></div>
		</div>
		<div id="subheader">
			<div style="float: right;">
				<a href="<?= ADMIN_ROOT ?>show_settings">Edit Show Settings</a>
			</div>
			<a href="/">View public site</a>
			|
			<a href="<?= ADMIN_ROOT ?>flushcache">Purge Homepage/RSS Caches</a>
		</div>

		<div id="inside">
			<?php echo $html->flash_errors(); ?>
			<?php echo $html->flash_notices(); ?>
			<?php echo $html->flash_successes(); ?>

			<?php echo $content_for_layout; ?>
		</div>

		<div id="footer">
			Copyright &copy; 2015, joshua stein
		</div>
	</div>
</body>
</html>
