<!DOCTYPE html>
<html>
	<head>
		<meta http-equiv="content-type" content="text/html; charset=utf-8" />
		<title><?= h($C->settings()->name) ?> Podcast<?= $C->page_title ? ": " .
			h($C->page_title) : "" ?></title>
		<link rel="shortcut icon" href="/favicon.png" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<? if (isset($C->meta_headers)) { ?>
			<? foreach ($C->meta_headers as $k => $v) { ?>
				<meta name="<?= h($k) ?>" content="<?= h($v) ?>" />
			<? } ?>
		<? } ?>
		<link rel="alternate" type="application/rss+xml" title="RSS Feed"
			href="<?= $C->settings()->url ?>episodes.rss"/>
		<style>
			body {
				color: #333;
				background-color: #fcfcfc;
				padding-bottom: 2em;
			}

			body, code {
				font-family: ubuntu mono, droid sans mono,
					inconsolata, menlo, courier new, monospace;
				font-size: 9pt;
			}
			code {
				background-color: #f0f0f0;
			}

			a {
				color: #1d71cc;
				display: inline-block;
			}
			a:visited {
				color: #6d95bf;
			}

			.na {
				color: gray;
			}

			.lead {
				margin-top: 3em;
				text-align: center;
			}

			.lead .show_title {
				font-size: 14pt;
			}

			.lead .logo {
				margin-bottom: 1em;
			}

			.lead .show_title a,
			.lead .logo a {
				text-decoration: none;
				color: #333;
			}

			p.subscribes {
				font-size: 10pt;
			}

			hr {
				border: 0;
				height: 1px;
				border-top: 1px solid #ddd;
				margin-top: 2em;
				margin-bottom: 2em;
				width: 600px;
			}

			.episodes, .episodes_pager {
				margin: 2em auto;
				width: 600px;
			}

			.episode .date {
				color: gray;
				font-size: 9pt;
			}

			.episode .title {
				font-size: 11pt;
				text-align: center;
				margin-bottom: 1em;
			}

			.episode audio,
			.episode .download {
				margin-left: auto;
				margin-right: auto;
				display: block;
				width: 500px;
			}
			.episode .download {
				margin-top: 0.5em;
				text-align: right;
				font-size: 8pt;
			}

			.episode .chapter {
				font-style: italic;
				text-decoration: none;
			}


			.episodes_pager {
				text-align: center;
			}

			@media only screen and (max-width: 480px) {
				body {
					margin: 5px 15px;
				}

				.episodes, .episodes_pager {
					width: 99%;
				}

				hr {
					width: 99%;
				}

				.episode audio,
				.episode .download {
					width: 95%;
				}
			}
		</style>
		<script>
			function episode_jump(obj, secs) {
				var p = document.getElementById(obj);
				if (!p) {
					console.log("can't find object " + obj);
					return;
				}

				p.play();
				p.currentTime = secs;
			}
		</script>
	</head>
	<body>
		<div class="lead">
			<div class="logo">
				<a href="/"><img src="/garbage-128.png"
					srcset="/garbage-128.png 1x, /garbage-256.png 2x"
					width=128 height=128></a>
			</div>

			<div class="show_title">
				<a href="/"><?= h($C->settings()->name) ?></a>
			</div>

			<p>
			<?= h($C->settings()->description) ?><br>
			by
			<? $h_lines = array(); ?>
			<? foreach ($C->hosts() as $host) { ?>
				<? array_push($h_lines, "<a href=\""
					. h($host->preferred_url) . "\">"
					. h($host->full_name) . "</a>"); ?>
			<? } ?>
			<?= $helper->comma_join($h_lines); ?>
			</p>

			<p class="subscribes">
			Subscribe:
			<a href="/episodes.rss">RSS</a>
			|
			<a href="<?= h($C->settings()->googleplay_url) ?>">Play Music</a>
			|
			<a href="<?= h($C->settings()->itunes_url) ?>">iTunes</a>
			|
			<a href="<?= h($C->settings()->pocketcasts_url) ?>">Pocket Casts</a>
			|
			<a href="<?= h($C->settings()->overcast_url) ?>">Overcast</a>
			</p>

			<p>
			Feedback:
			<a href="https://twitter.com/<?=
				h($C->settings()->twitter_username) ?>">Twitter</a>
			|
			<a href="mailto:<?= h($C->settings()->contact_email) ?>">E-mail</a>
			</p>

			<hr>
		</div>

		<?php echo $content_for_layout; ?>
	</body>
</html>
