<?= $html->error_messages_for($episode); ?>

<div class="boxline">
<?= $f->label("episode", "Episode Number:", array("class" => "required")); ?>
<?= $f->text_field("episode", array("style" => "width: 2em;")); ?>
</div>

<div class="boxline">
<?= $f->label("is_pending", "Pending:", array("class" => "required")); ?>
<?= $f->check_box("is_pending") ?> (Will not show up on the website or RSS
feeds)
</div>

<div class="boxline">
<?= $f->label("air_date", "Date:", array("class" => "required")); ?>
<?= $f->text_field("air_date", array("style" => "width: 300px;",
	"value" => $f->form_object->air_date->format("Y-m-d H:i"))); ?>
</div>

<div class="boxline">
<?= $f->label("title", "Title:", array("class" => "required")); ?>
<?= $f->text_field("title", array("style" => "width: 300px;")); ?>
</div>

<!--
<div class="boxline">
<?= $f->label("summary", "Summary:", array("class" => "required")); ?>
<?= $f->text_field("summary", array("style" => "width: 500px;")); ?>
</div>
-->

<div class="boxline">
<?= $f->label("custom_artwork_url", "Custom Artwork URL:",
	array("class" => "required")); ?>
<?= $f->text_field("custom_artwork_url", array("style" => "width: 500px;",
	"placeholder" => "Must be absolute URL")) ?>
</div>

<div class="boxline">
<?= $f->label("is_explicit", "Explicit Content:", array("class" => "required")); ?>
<?= $f->check_box("is_explicit") ?>
</div>

<div class="boxline">
<?= $f->label("duration", "Duration:", array("class" => "required")); ?>
<?= $f->text_field("duration", array("style" => "width: 5em;")) ?>
	<span class="na">((h:)?m?m:ss)</span>
</div>

<? if ($f->form_object->id) { ?>
	<div class="boxline">
	<?= $f->label("filesize", "File size:", array("class" => "required")); ?>
	<span class="d">
		<?= $helper->bytes_h($f->form_object->filesize) ?> bytes
	</span>
	</div>
<? } ?>

<div class="boxline">
<?= $f->label("new_mp3", ($f->form_object->id ? "Replace " : "")
	. "MP3 file:", array("class" => "required")); ?>
<?= $f->file_field("new_mp3") ?>
</div>

<div class="boxline">
<?= $f->label("notes", "Show Notes:", array("class" => "required")); ?>
</div>
<div class="boxline">
<?= $f->text_area("notes", array("class" => "fixed",
	"style" => "width: 400px; height: 350px; font-size: 9pt;")); ?>
<div id="previews" style="display: inline-block; width: 400px; height: 350px;
margin-left: 10px;">
</div>

<script>
var update_running = false;
function update_preview() {
	if (update_running)
		return;
	else
		update_running = true;

	new Ajax.Updater("previews", "<?= ADMIN_ROOT_URL ?>episodes/md_preview", {
		method: "post",
		parameters: {
			"preview_text": $("episode_notes").value,
			"authenticity_token" : "<?= $C->form_authenticity_token() ?>",
		},
		onComplete: function() { update_running = false; },
	});
}

new Form.Element.Observer("episode_notes", 0.5, function(el, value) {
	update_preview();
});

update_preview();

</script>
