<div style="float: right;">
	<strong>
	<?= $html->link_to("Delete",
		ADMIN_ROOT_URL . "episodes/destroy/" . $episode->episode,
		array("confirm" => "Are you sure you want to delete this episode?",
			"method" => "post")); ?>
	</strong>
	|
	<strong><a href="<?= ADMIN_ROOT_URL ?>">Cancel</a></strong>
</div>

<? if ($C->episode->title && !$C->episode->is_pending) { ?>
	<h3>Announce Episode <?= h($episode->episode) ?></h3>

	<div class="box wide">
	<? $form->form_tag(ADMIN_ROOT_URL . "episodes/tweet", array(),
	function($f) use ($C, $helper) { ?>
		<div class="boxline">
		<?= $f->text_area_tag("tweet",
			strtolower($helper->settings()->name)
			. "[" . $C->episode->episode . "]: " . $C->episode->title . "\n"
			. $C->episode->absolute_url); ?>
		<?= $f->submit_tag("Tweet"); ?>
		</div>
	<? }); ?>
	</div>
<? } ?>

<h3>Edit Episode <?= h($episode->episode) ?></h3>

<div class="box wide">
	<? $form->form_for($C->episode, ADMIN_ROOT_URL . "episodes/update/" .
	$episode->episode, array("multipart" => true), function($f) use ($C) { ?>
		<?= $C->render(array("partial" => "form"), array("f" => $f)); ?>
		<p>
		<?= $f->submit_tag("Update"); ?>
		</p>
	<? }); ?>
</div>
