<div class="episode">
	<div class="title">
		<a href="<?= h($episode->absolute_url) ?>"><?= h($episode->full_title)
			?></a>
		<div class="date">
			<?= $episode->air_date->format("F jS, Y") ?>
		</div>
	</div>

	<audio controls id="episode_player_<?= $episode->episode ?>" preload="none">
		<source src="<?= h($episode->mp3_url) ?>" type="audio/mpeg">
		Your browser does not support the audio element -
	</audio>
	<div class="download">
		<a href="<?= h($episode->mp3_url) ?>">Download
			(<?= $helper->bytes_h($episode->filesize) ?>)</a>
	</div>

	<div class="notes">
		<? foreach (explode("\n", $episode->notes_html) as $line) { ?>
			<?= preg_replace_callback("/<!-- ([0-9:]+) -->/",
				function($m) use ($helper, $episode) {
					return " <a href=\"#\" class=\"chapter\" "
						. "onclick=\"episode_jump('episode_player_"
						. $episode->episode . "', '"
						. $helper->time_to_secs($m[1])
						. "'); return false;\">(" . h($m[1]) . ")</a>";
				}, $line) ?>
		<? } ?>
	</div>
</div>
