<div class="episodes">
	<? foreach ($episodes as $x => $episode) { ?>
		<?= $C->render(array("partial" => "episode"),
			array("episode" => $episode)); ?>

		<? if ($x < count($episodes) - 1) { ?>
			<hr>
		<? } ?>
	<? } ?>
</div>

<? if (isset($C->page)) { ?>
	<div class="episodes_pager">
		<hr>

		<? if ($C->page > 0) { ?>
			<a href="/page/<?= h($C->page - 1) ?>">&lt;&lt;</a>
		<? } else { ?>
			<span class="na">&lt;&lt;</span>
		<? } ?>

		pages[<a href="/page/<?= h($C->page) ?>"><?= h($C->page) ?></a>]

		<? if ($C->page < $C->pages) { ?>
			<a href="/page/<?= h($C->page + 1) ?>">&gt;&gt;</a>
		<? } else { ?>
			<span class="na">&gt;&gt;</span>
		<? } ?>
	</div>
<? } ?>
