<? if (isset($C->page) && $C->page > 0) { ?>
	<?= $C->render(array("partial" => "pager")); ?>
<? } ?>

<div class="episodes">
	<? foreach ($episodes as $x => $episode) { ?>
		<?= $C->render(array("partial" => "episode"),
			array("episode" => $episode)); ?>

		<? if ($x < count($episodes) - 1) { ?>
			<hr>
		<? } ?>
	<? } ?>
</div>

<? if (isset($C->page)) { ?>
	<hr>
	<?= $C->render(array("partial" => "pager")); ?>
<? } ?>
