<!DOCTYPE html>
<html>
	<head>
		<meta http-equiv="content-type" content="text/html; charset=utf-8" />
		<title><?= h($C->settings()->name) ?> Podcast<?= $C->page_title ? ": " .
			h($C->page_title) : "" ?></title>
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<style>
			body {
				margin: 0;
				background-color: #fcfcfc;
				font-family: sans-serif;
				font-size: 10pt;
			}
			a {
				color: gray;
			}
		</style>
	</head>
	<body>
		<div style="width: 20%; float: left;">
			<img src="<?= h($C->episode->secure_artwork_url) ?>" width="100%">
		</div>

		<div style="width: 80%; margin-left: 20%;">
			<audio controls id="episode_player_<?= $C->episode->episode ?>"
			<?= $C->params["autoplay"] == 1 ? "autoplay" : "" ?>
			style="width: 95%; padding-top: 2em;">
				<source src="<?= h($C->episode->secure_mp3_url) ?>" type="audio/mpeg">
				Your browser does not support the audio element
			</audio>
			<p>
			<strong>Show notes:</strong>
			<a href="<?= h($C->episode->absolute_url) ?>" target="_blank"><?=
				h($C->episode->absolute_url) ?></a>
			</p>
		</div>

		<div style="clear: both;"></div>
	</body>
</html>
